### ISSUE TITLE
Jumping to empty line not working

### ISSUE THREAD

**Issue by martin-hyca** [ArturoDent/jump-and-select#11]
I have this in my keybindings.json, alongside other stuff reltaed to jump and select. It seems not to be working. I also tried with a simplier key combination (which works for other stuff reliably, stuff I deactivated for that testing), no success. Any idea what I could try?

```
    {
        "key": "cmd+shift+alt+g",
        "command": "jump-and-select.jumpForwardSelect",
        "args": {
          "text": "^$"   // select to next empty line
        }
    },
```

**Comment by ArturoDent** [comment]
There was a "bug".  This extension searches through the text of the file.  For various reasons vscode "normalizes" newlines (for cross-OS purposes) so that the retrieved text includes `\r\n`'s where `\n`'s occur.  This makes searching for empty lines not as simple as `^$` but it works.

But for a very few files, like `keybindings.json`, `.vscode/tasks.json` and `.code-snippets` it does not do the normalization!!  It does for `settings.json` and `launch.json` for some reason.  So I bet you were trying to use your keybinding in `keybindings.json`.

It should be fixed in v0.5.3.  Please let me know.  Thans.

**Comment by martin-hyca** [comment]
great, works, thanks 🙂

**Comment by martin-hyca** [comment]
actually testing in keybindings.json worked fine, but in a .py, .html.j2 and .css file, it jumps at the end of the file - as long as there is an empty line at the end, ignoring any other empty lines.

**Comment by ArturoDent** [comment]
It may be OS-dependent as well as language-dependent.  I tried a more generic fix.  Please try v0.5.4.

**Comment by martin-hyca** [comment]
Still no luck, same behaviour. In a new document without language specified, it also jumps to end of the file if there is an empty line, otherwise no jumping. 
I am on MacOS. 
It would be super cool to have this working, I would be using this a lot!

**Comment by ArturoDent** [comment]
I updated the extension to v0.6.0 with some significant changes to the settings so be sure to check out the README.

I tried another route to handling jumps to empty lines so let me know if this version works.  I am trying to avoid loading WSL and a Linux distro on this laptop...

**Comment by martin-hyca** [comment]
Finally got to it.

Seems to be working great, thanks a lot for the fix.
The only caveat for me was that the jumping to empty new lines works only for `empty` lines. Whenever there are whitespaces or tabs, the match will fail. 

I installed the "Trailling Spaces" extension to be able to spot and delet these easily. 
However, my preference would still be to be able to jump to empty lines *with* whitespaces / tabs in them.

**Comment by martin-hyca** [comment]
two more things: 
- for me the best would be to be able to jump to new lines during the `multi mode`. Any ideas how this could work? TAB, for example, seems not to be matching, instead, it *writes out* tab...  could this be translated to new line? Or some F key possibly? 
- when jumping by white spaces, it would kind of make sense to ignore consecutive white spaces. If I "land" on a new line which begins with, say, 20 white spaces, and I want to jump to the next white space, expected behaviour would be to jump to the next NON-consecutive white space. May be I wrote this already couple of months ago, 
anyways, now my shortcuts are finally properly set and I am able to use it in my job, so thanks a lot and - in case you feel like developping this further - I should be able to provide more feedback as time goes by.
